### ISSUE TITLE
How many rpc messages?

### ISSUE THREAD

**Issue by nilsocket** [canonical/raft#100]
How many rpc messages does this implementation does leader node initiate to send a message in 3-node cluster.

I tried checking with wireshark, but it contains too much of clutter from raft ports, where raft is listening, can you once see if, everything is fine. I have checked it with `v0.9.9`. I tried to check with `v0.9.13`, as API seems to have changed I didn't go with re-writing for this, as my code is already a mess.

When I have checked with wireshark, there were too many tcp ack's, being sent with other nodes.

I have configured heartbeat to 300ms, but messages were around >100 within second.

Thank you.

**Comment by freeekanayaka** [comment]
After a leader gets elected, when idle it will send about ```1``` AppendEntries RPC message every ```heartbeat_timeout``` milliseconds to each of the other nodes, and when receiving entries from a client request (via ```raft_apply()```) it will send ```1``` AppendEntries RPC message immediately to all other nodes (assuming if they have entered pipeline mode, which happens after the leader receives acknowledgement of the very first AppendEntries).

**Comment by freeekanayaka** [comment]
Note that the API is expected to change slightly until we reach a final ```v1.0.0``` release.

**Comment by nilsocket** [comment]
I mean no.of times you go and back through the network (I'm don't know exact technical term for this), for example:
For sending data initially(appendEntries), 
then for a confirmation that node have received.
and once majority of them have received, informing to apply (for calling `fsm_apply()`).
3?

Am I right, or it includes anything else.

Anyhow I will try to test with latest version and update once again.
Thank you.

**Comment by freeekanayaka** [comment]
To know the details about this, probably the best source is the [Raft dissertation](https://github.com/ongardie/dissertation#readme).

Anyway, in a "normal" situation for a cluster of 3 servers I would expect:

0) Client submits a request to apply a new entry, using ```raft_apply```
1) Leader immediately sends 2 AppendEntry RPC messages to the 2 followers.
3) The followers send 2 AppendEntryResult RPC messages to the leader.
4) As soon as the leader receives 1 AppendEntryResult RPC, it has a quorum and will call ```fsm->apply()```

So ```fsm->apply()``` will be called after 3 RPCs have been fully completed. A fourth RPC will still be made by the slower follower, but won't count for commitment.

Please note that what I described happens during "normal" operation, e.g. once the leader has been elected and has been stable, and once followers have caught up with any previous backlog entries they didn't have. In those cases you'll have more RPCs involved in order to get to "normal" operation.

**Comment by nilsocket** [comment]
I read the Raft dissertation, I'm asking as a confirmation for your implementation.

Thanks a lot for your reply.

Anyway, While trying to compile in CentOS, during `./configure --enable-example` it fails, saying `libuv` is not available.

Finding the cause took sometime, as I didn't experience this in Ubuntu, since I'm new and don't know much.
exporting `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig` fixed.

I don't know much about C's build systems, don't you think its better to have it configured in raft's build as it is kind of default path in most library installations.

Thank you.

**Comment by freeekanayaka** [comment]
It feels this is something that should be fixed in CentOS. On Ubuntu the ```/usr/local/lib/pkgconfig``` path is part of the default search paths of pkg-config:

```
~$ pkg-config --variable pc_path pkg-config
/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
```

What does ```pkg-config --variable pc_path pkg-config``` return on your CentOS installation? You might want to file a bug against the pkg-config package on CentOS if the default search paths don't include ```/usr/local/lib/pkgconfig```.

**Comment by nilsocket** [comment]
```
[root@a52d27ce0a37 /]# pkg-config --variable pc_path pkg-config
/usr/lib64/pkgconfig:/usr/share/pkgconfig
```
I will report it there.

Thank you.
