### ISSUE TITLE
It seems that syscall is only required in uv_*.c

### ISSUE THREAD

**Issue by LuminousXLB** [canonical/raft#125]
But the file `src/syscall.c` is required even though `UV_ENABLED` is disabled in [Makefile.am](https://github.com/canonical/raft/blob/master/Makefile.am#L36)

Is it really essential when libuv is disabled?

**Comment by freeekanayaka** [comment]
It's not essential, but I placed it in the top-level core because it might be useful for implementing other non-libuv based backends in the future.

Does it create problems for you?

Right now it might prevent building on non-linux platform, but I can easily put some #ifdef's to skip building linux-specific parts on non-linux. Would that be enough?

**Comment by Kerollmops** [comment]
Hey @freeekanayaka,

I would be really interrested on those #ifdef's you are talking about, I am currently working on OSX and everytime I need to test the work I do I need to rsync it to a remote linux machine and compile there.

Would be glad if you help me, and probably others, compile on any OS :)

**Comment by freeekanayaka** [comment]
> I am currently working on OSX 

Do you mean you are just **developing** on OSX and you're actual target deployment target is Linux, or that you actually want to use libraft on OSX?

In the latter case you might want to look at @AshfordN's work on the Windows port, #119 .

**Comment by Kerollmops** [comment]
I am actually developping on OSX and targeting linux.

But in a near future I would like to be able to run libraft on any platform, I already saw #119 and it seems really promising as the only part that is missing is the Windows support IIUC :)

I just opened #130 to explain a little bit more about the work I want to achieve.
