### ISSUE TITLE
Potential use-after-free in handling of raft_transfer

### ISSUE THREAD

**Issue by cole-miller** [canonical/raft#396]
When raft_transfer is called, if the UvSend connection pool is all occupied, we end up putting a message in the "pending" queue that holds a pointer to the transfer object:

https://github.com/canonical/raft/blob/c36072c4606aeb2fd53a2f66bf1e3378cebf0e2f/src/membership.c#L217

https://github.com/canonical/raft/blob/c36072c4606aeb2fd53a2f66bf1e3378cebf0e2f/src/uv_send.c#L214

The pending transfer has an associated timeout, and if that expires, we abort the attempt:

https://github.com/canonical/raft/blob/c36072c4606aeb2fd53a2f66bf1e3378cebf0e2f/src/tick.c#L232-L239

And invoke the callback:

https://github.com/canonical/raft/blob/c36072c4606aeb2fd53a2f66bf1e3378cebf0e2f/src/membership.c#L226-L234

But the send request associated with the transfer is still sitting in the pending queue, and so its callback might get invoked a second time, for example when evicting the last message here:

https://github.com/canonical/raft/blob/c36072c4606aeb2fd53a2f66bf1e3378cebf0e2f/src/uv_send.c#L312-L330

This can quickly lead to a use-after-free when the transfer callback owns some memory; I ran into it while debugging https://github.com/canonical/dqlite/pull/480.

**Comment by freeekanayaka** [comment]
I didn't look at this much in depth, but I noticed that when the message is sent here:

https://github.com/canonical/raft/blob/c36072c4606aeb2fd53a2f66bf1e3378cebf0e2f/src/membership.c#L217

no callback parameter is passed to `send()` (the last argument of the call is `NULL`). IIRC that's done on purpose, because we're not only interested in knowning if the sending succeeds, but also if the receiver gets it correctly and manages to become leader. So we ignore the callback and rather watch for a leader change.

This means that when the message is evicted here:

https://github.com/canonical/raft/blob/c36072c4606aeb2fd53a2f66bf1e3378cebf0e2f/src/uv_send.c#L312-L330

no callback should be invoked.

So if `membershipLeadershipTransferClose` gets called twice it might be because of something else. Am I missing something?

**Comment by freeekanayaka** [comment]
If my impression is confirmed, it feels like a misdesign of the `struct raft_transfer` object, because it couples the lifetime of the `struct raft_io_send` object with the lifetime of `struct raft_transfer` itself.

I'd suggest to then modify the `membershipLeadershipTransferStart()` to **not** use the `struct raft_io_send` object embedded in `struct raft_transfer`, but rather allocate a new one, whose lifetime is independent.

Something like:

```diff
diff --git a/src/membership.c b/src/membership.c
index bc563b3..f608581 100644
--- a/src/membership.c
+++ b/src/membership.c
@@ -4,6 +4,7 @@
 #include "assert.h"
 #include "configuration.h"
 #include "err.h"
+#include "heap.h"
 #include "log.h"
 #include "progress.h"
 #include "tracing.h"
@@ -194,10 +195,16 @@ void membershipLeadershipTransferInit(struct raft *r,
     r->transfer = req;
 }
 
+static void membershipLeadershipSendCb(struct raft_io_send *send, int status) {
+    (void)status;
+    RaftHeapFree(send);
+}
+
 int membershipLeadershipTransferStart(struct raft *r)
 {
     const struct raft_server *server;
     struct raft_message message;
+    struct raft_io_send *send;
     int rv;
     assert(r->transfer->send.data == NULL);
     server = configurationGet(&r->configuration, r->transfer->id);
@@ -207,15 +214,37 @@ int membershipLeadershipTransferStart(struct raft *r)
         return -1;
     }
 
+    /* Don't use the raft_io_send object embedded in struct raft_transfer, since
+     * the two objects must have different lifetimes. For example raft_io_send
+     * might live longer than raft_transfer, see #396.
+     *
+     * Ideally we should remove the embedded struct raft_io_send send field from
+     * struct raft_transfer, and replace it with a raft_io_send *send pointer,
+     * that we set to the raft_io_send object allocated in this function. This
+     * would break ABI compatibility though. */
+    send = RaftHeapMalloc(sizeof *send);
+    if (send == NULL) {
+        return RAFT_NOMEM;
+    }
+
     message.type = RAFT_IO_TIMEOUT_NOW;
     message.server_id = server->id;
     message.server_address = server->address;
     message.timeout_now.term = r->current_term;
     message.timeout_now.last_log_index = logLastIndex(r->log);
     message.timeout_now.last_log_term = logLastTerm(r->log);
+
+    /* Set the data attribute of the raft_io_send object embedded in
+     * raft_transfer. This is needed because we historically used it as a flag
+     * to indicate that a transfer request was sent. See the replicationUpdate
+     * function. */
     r->transfer->send.data = r;
-    rv = r->io->send(r->io, &r->transfer->send, &message, NULL);
+
+    send->data = r;
+
+    rv = r->io->send(r->io, send, &message, membershipLeadershipSendCb);
     if (rv != 0) {
+        RaftHeapFree(send);
         ErrMsgTransferf(r->io->errmsg, r->errmsg, "send timeout now to %llu",
                         server->id);
         return rv;
```

This would be a conservative approach to avoid changing `struct raft_transfer` at all. In practice, I believe that changing `struct raft_transfer` would be actually fine (for dqlite and any other clients). It would be:

```diff
--- a/include/raft.h
+++ b/include/raft.h
@@ -1051,7 +1051,7 @@ struct raft_transfer
     RAFT__REQUEST;
     raft_id id;               /* ID of target server. */
     raft_time start;          /* Start of leadership transfer. */
-    struct raft_io_send send; /* For sending TimeoutNow */
+    struct raft_io_send *send; /* For sending TimeoutNow */
     raft_transfer_cb cb;      /* User callback */
 };
 ```

and since the new structure is smaller than the old one and dqlite (or other clients) must access only the `data` field (the very first one of `struct raft_transfer`, defined by `RAFT__REQUEST`, which the only public field, the rest is private), nothing would break.
