### ISSUE TITLE
src/log.c:87: refsTryInsert: Assertion `next_slot->term != term' failed.

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/raft#470]
Detected in Jepsen: https://github.com/canonical/jepsen.dqlite/actions/runs/5953700449/job/16148585347
[jepsen-data-bank-partition,disk-failure(2).zip](https://github.com/canonical/raft/files/12421760/jepsen-data-bank-partition.disk-failure.2.zip)

**Comment by freeekanayaka** [comment]
> Ahh, and importantly:
> 
> * n3 is the leader in term 2, and its disk write for the entry at 3969 fails, causing it to step down
> 
> So I think the cleanup after the disk write failure must be buggy, missing a refcount decrement maybe

My 2c: when `struct raft_io` reports a disk write failure (i.e. `raft_io->append()`'s callback fires with a non-zero `status`), `struct raft` should somehow schedule a `raft_io->append` retry later in the future, rather than rolling back its own in-memory log and rely on the leader to resend everything and retrigger the whole behavior. Rolling back is always hard and it's easy to miss details, while retrying should be relatively straighforward (or at least it limits any rollback logic to the internals of `struct raft_io`).

In case the write failure is `ENOSPC` the follower `struct raft` could also take note of that and stop accepting new AppendEntries messages until the situation resolves.

**Comment by cole-miller** [comment]
(fixed by #483)
