### ISSUE TITLE
CI: `xfs` test failures

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/raft#481]
Suddenly a couple of unit tests using `xfs` started failing during a test run of an unrelated PR.

See https://github.com/canonical/raft/actions/runs/6219694707/job/16878253617

**Comment by freeekanayaka** [comment]
The kernel in GitHub runners was recently upgraded from 5.4 to 6.2.

FWIW I've fixed it with this https://github.com/cowsql/raft/pull/53/files (which incidentally makes the btrfs test pass too, since it's the same situation). The test is not deterministic anymore, but so is the underlying kernel logic.
